name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Fix Icon Format
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        for dir in app/src/main/res/mipmap-*; do
          if [ -f "$dir/ic_launcher.png" ]; then
            mogrify -format png "$dir/ic_launcher.png"
          fi
        done

    - name: Generate Gradle Wrapper
      run: gradle wrapper --gradle-version 8.4

    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon

    - name: Sign Release APK
      run: |
        # Автоматическая генерация ключа
        keytool -genkey -v -keystore app.keystore -alias appalias -keyalg RSA -keysize 2048 -validity 10000 -storepass apppassword -keypass apppassword -dname "CN=ZaymNaKartu, OU=ZNK, O=ZNK, L=Moscow, S=Moscow, C=RU"
        
        # Настройка утилит Android для подписи
        BUILD_TOOLS=$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
        
        # Подготовка и подпись APK файла
        $BUILD_TOOLS/zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app-release-aligned.apk
        $BUILD_TOOLS/apksigner sign --ks app.keystore --ks-pass pass:apppassword --key-pass pass:apppassword --out ZaymNaKartu-Release-Signed.apk app-release-aligned.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: ZaymNaKartu-Release-Signed
        path: ZaymNaKartu-Release-Signed.apk

